[package]
authors = ['Unique One <hello@uniqueone.network>']
description = 'Unique One Appchain Node.'
edition = '2018'
homepage = 'https://uniqueone.network/'
license = 'Apache-2.0'
name = 'uniqueone-appchain'
publish = false
repository = 'https://github.com/octopus-network/barnacle/'
version = '1.0.1'
build = 'build.rs'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[[bin]]
name = 'uniqueone-appchain'
[build-dependencies.substrate-build-script-utils]
git = 'https://github.com/paritytech/substrate.git'
branch = 'polkadot-v0.9.8'

[dependencies.uniqueone-appchain-runtime]
path = '../runtime'
version = '1.0.1'

[dependencies]
jsonrpc-core = '15.1.0'
structopt = '0.3.8'

rand = "0.7.2"

sc-chain-spec = { branch = 'polkadot-v0.9.8', git = "https://github.com/paritytech/substrate.git" }
sc-consensus-babe-rpc = { branch = 'polkadot-v0.9.8', git = "https://github.com/paritytech/substrate.git" }
sc-consensus-epochs = { branch = 'polkadot-v0.9.8', git = "https://github.com/paritytech/substrate.git" }
sc-consensus-slots = { branch = 'polkadot-v0.9.8', git = "https://github.com/paritytech/substrate.git" }
sc-consensus-uncles = { branch = 'polkadot-v0.9.8', git = "https://github.com/paritytech/substrate.git" }
sc-finality-grandpa-rpc = { branch = 'polkadot-v0.9.8', git = "https://github.com/paritytech/substrate.git" }
sc-network = { branch = 'polkadot-v0.9.8', git = "https://github.com/paritytech/substrate.git" }
sc-sync-state-rpc = { branch = 'polkadot-v0.9.8', git = "https://github.com/paritytech/substrate.git" }
sp-authorship = { branch = 'polkadot-v0.9.8', git = "https://github.com/paritytech/substrate.git" }
sp-keystore = { branch = 'polkadot-v0.9.8', git = "https://github.com/paritytech/substrate.git" }
pallet-im-online = { branch = 'polkadot-v0.9.8', git = "https://github.com/paritytech/substrate.git" }
pallet-mmr-rpc = { branch = 'polkadot-v0.9.8', git = "https://github.com/paritytech/substrate.git" }
sp-transaction-pool = { branch = 'polkadot-v0.9.8', git = "https://github.com/paritytech/substrate.git" }

beefy-primitives = { version = "0.1.0", git = "https://github.com/octopus-network/grandpa-bridge-gadget", branch = "dev" }
beefy-gadget = { version = "0.1.0", git = "https://github.com/octopus-network/grandpa-bridge-gadget", branch = "dev" }
beefy-gadget-rpc = { version = "0.1.0", git = "https://github.com/octopus-network/grandpa-bridge-gadget", branch = "dev" }

#pallet-octopus-appchain = { git = "https://github.com/octopus-network/octopus-pallets", branch = "main" }
#pallet-octopus-lpos = { git = "https://github.com/octopus-network/octopus-pallets", branch = "main" }
pallet-octopus-appchain = { git = 'https://github.com/blocksphereid/octopus-pallets.git', branch = 'polkadot-v0.9.8' }
pallet-octopus-lpos = { git = 'https://github.com/blocksphereid/octopus-pallets.git', branch = 'polkadot-v0.9.8' }


[dependencies.frame-benchmarking]
git = 'https://github.com/paritytech/substrate.git'
branch = 'polkadot-v0.9.8'

[dependencies.frame-benchmarking-cli]
git = 'https://github.com/paritytech/substrate.git'
branch = 'polkadot-v0.9.8'

[dependencies.pallet-transaction-payment-rpc]
git = 'https://github.com/paritytech/substrate.git'
branch = 'polkadot-v0.9.8'

[dependencies.sc-basic-authorship]
git = 'https://github.com/paritytech/substrate.git'
branch = 'polkadot-v0.9.8'

[dependencies.sc-cli]
features = ['wasmtime']
git = 'https://github.com/paritytech/substrate.git'
branch = 'polkadot-v0.9.8'

[dependencies.sc-client-api]
git = 'https://github.com/paritytech/substrate.git'
branch = 'polkadot-v0.9.8'

[dependencies.sc-consensus]
git = 'https://github.com/paritytech/substrate.git'
branch = 'polkadot-v0.9.8'

[dependencies.sc-consensus-babe]
git = 'https://github.com/paritytech/substrate.git'
branch = 'polkadot-v0.9.8'

[dependencies.sc-executor]
features = ['wasmtime']
git = 'https://github.com/paritytech/substrate.git'
branch = 'polkadot-v0.9.8'

[dependencies.sc-finality-grandpa]
git = 'https://github.com/paritytech/substrate.git'
branch = 'polkadot-v0.9.8'

[dependencies.sc-keystore]
git = 'https://github.com/paritytech/substrate.git'
branch = 'polkadot-v0.9.8'

[dependencies.sc-rpc]
git = 'https://github.com/paritytech/substrate.git'
branch = 'polkadot-v0.9.8'

[dependencies.sc-rpc-api]
git = 'https://github.com/paritytech/substrate.git'
branch = 'polkadot-v0.9.8'

[dependencies.sc-service]
features = ['wasmtime']
git = 'https://github.com/paritytech/substrate.git'
branch = 'polkadot-v0.9.8'

[dependencies.sc-telemetry]
git = 'https://github.com/paritytech/substrate.git'
branch = 'polkadot-v0.9.8'

[dependencies.sc-transaction-pool]
git = 'https://github.com/paritytech/substrate.git'
branch = 'polkadot-v0.9.8'

# [dependencies.sc-transaction-pool-api]
# git = 'https://github.com/paritytech/substrate.git'
# tag = 'monthly-2021-08'
# version = '3.0.0'

[dependencies.sp-api]
git = 'https://github.com/paritytech/substrate.git'
branch = 'polkadot-v0.9.8'

[dependencies.sp-block-builder]
git = 'https://github.com/paritytech/substrate.git'
branch = 'polkadot-v0.9.8'

[dependencies.sp-blockchain]
git = 'https://github.com/paritytech/substrate.git'
branch = 'polkadot-v0.9.8'

[dependencies.sp-consensus]
git = 'https://github.com/paritytech/substrate.git'
branch = 'polkadot-v0.9.8'

[dependencies.sp-consensus-babe]
git = 'https://github.com/paritytech/substrate.git'
branch = 'polkadot-v0.9.8'

[dependencies.sp-core]
git = 'https://github.com/paritytech/substrate.git'
branch = 'polkadot-v0.9.8'

[dependencies.sp-finality-grandpa]
git = 'https://github.com/paritytech/substrate.git'
branch = 'polkadot-v0.9.8'

[dependencies.sp-inherents]
git = 'https://github.com/paritytech/substrate.git'
branch = 'polkadot-v0.9.8'

[dependencies.sp-runtime]
git = 'https://github.com/paritytech/substrate.git'
branch = 'polkadot-v0.9.8'

[dependencies.sp-timestamp]
git = 'https://github.com/paritytech/substrate.git'
branch = 'polkadot-v0.9.8'

[dependencies.substrate-frame-rpc-system]
git = 'https://github.com/paritytech/substrate.git'
branch = 'polkadot-v0.9.8'

[features]
default = []
runtime-benchmarks = ['uniqueone-appchain-runtime/runtime-benchmarks']
